def branch = env.BRANCH_NAME
def build = env.BUILD_NUMBER
def appname = "helloworld"
def artifactory = "docker.io" 
def repo = "elevy99927" 
def appimage = "${repo}/${appname}"
def apptag = "${build}"

podTemplate(containers: [
      containerTemplate(name: 'jnlp', image: 'jenkins/inbound-agent', ttyEnabled: true),
      containerTemplate(name: 'docker', image: 'gcr.io/kaniko-project/executor:v1.23.0-debug', command: '/busybox/cat', ttyEnabled: true)
  ],
  volumes: [
     configMapVolume(mountPath: '/kaniko/.docker/', configMapName: 'docker-cred')
  ])  {
    node(POD_LABEL) {
        stage('checkout') {
            container('jnlp') {
                sh '/usr/bin/git config --global http.sslVerify false'
                checkout scm
            }
        }

        stage('build') {
            container('docker') {
                echo "Building docker image with Kaniko..."
                echo "/kaniko/executor --force --dockerfile=Dockerfile --context=dir://${env.WORKSPACE} --destination=${appimage}:${apptag}"
                sh "/kaniko/executor --force --context=dir://${env.WORKSPACE} --destination=${appimage}:${apptag}"


            }
        }

        stage('deploy') {
            container('jnlp') {
                echo "helm install myapp"
            }
        }

        stage('push-yaml') {
            container('jnlp') {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    sh '''
                        git config user.email "jenkins@example.com"
                        git config user.name "Jenkins"
                        git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/elevy99927/hello-newapp.git
                        git add *.yaml *.yml
                        git commit -m "Update YAML files - Build ${BUILD_NUMBER}"
                        git push origin HEAD:${BRANCH_NAME}
                    '''
                }
            }
        }
    }
}