apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: Project allowing apps from a specific Git repo
  sourceRepos:
    - https://github.com/elevy99927/*
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
