apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: projects-qa-only
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - project: project-1
            cluster: k8s-qa
          - project: project-2
            cluster: k8s-qa
  template:
    metadata:
      name: '{{.project}}-{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/elevy99927/argo-demo-repo.git
        targetRevision: application
        path: '{{.project}}/{{.cluster}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.project}}-{{.cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true